# Basic concepts of tensorflow

* Introduction to tensors
* Getting Information from tensors
* Manipulating Tensors
* Tensors and Numpy
* Using @tf.function ( a way to speed up the python code)


In [2]:
import tensorflow as tf

print(tf.__version__)

2.8.2


In [ ]:
# create a tensor with tf.constant()

scaler = tf.constant(10)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
scaler.ndim

0

In [ ]:
# create a vector

vector =  tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# create a matrix

matrix = tf.constant([[10,9],[20,11]])
matrix.ndim

2

In [ ]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  9],
       [20, 11]], dtype=int32)>

In [ ]:
matrix.shape

TensorShape([2, 2])

In [ ]:
# The rank of a tensor is the number of indices required to uniquely select each element of the tensor. 
# Rank is also known as "order", "degree", or "ndims.

tf.rank(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Creating tensors with tf.Varaible

In [ ]:
tensor_var = tf.Variable([19,20])
tensor_const = tf.constant([19,20])

print(tensor_var)
print(tensor_const)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([19, 20], dtype=int32)>
tf.Tensor([19 20], shape=(2,), dtype=int32)


In [ ]:
tensor_var[0].assign(20)
tensor_var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([20, 20], dtype=int32)>

In [ ]:
tensor_const[0] = 10

TypeError: ignored

**Note:** We can't change tf.constant() it is immutable but we can change values in tf.Variable()

#### Creating Random Tensors

In [ ]:
random = tf.random.Generator.from_seed(40)
random = random.normal(shape=(4,5))
random

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 0.78953624,  0.53897345, -0.48535708,  0.74055266,  0.31662667],
       [-1.4391748 ,  0.58923835, -1.4268045 , -0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 , -0.23193763, -1.8107855 ,  0.09988727],
       [-0.50998646, -0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
      dtype=float32)>

In [ ]:
# Create a tensor with ones

tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor with zeros

tf.zeros(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Convert a numpy array to a tensor

In [2]:
import numpy as np

In [3]:
numpy_arr = np.arange(1,25)

tensor_np = tf.constant(numpy_arr)
tensor_np

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [4]:
## Rank of Tensor: Number of tensor dimensions

rank_3 = tf.ones(shape=[3,2,2])
rank_3

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [7]:
# get 1st col of tensor 

rank_3[:,:2,:1]

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

## Tensor Basic Operation

In [9]:
tensor = tf.constant([[15,2],[8,7]])

# Tensor Addition
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 12],
       [18, 17]], dtype=int32)>

In [10]:
# Tensor Multiplication

tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30,  4],
       [16, 14]], dtype=int32)>

In [12]:
# Tensor Substraction

tensor - 1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14,  1],
       [ 7,  6]], dtype=int32)>

In [13]:
# TensorFlow function for tensor multiplication

tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[150,  20],
       [ 80,  70]], dtype=int32)>

### Matrix Multiplication using tf.matmul()

In [14]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[241,  44],
       [176,  65]], dtype=int32)>

In [15]:
# Matrix multiplication with operator @

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[241,  44],
       [176,  65]], dtype=int32)>

In [16]:
# Define new Matrix

mat1 = tf.constant([[2,3,5],[6,1,3]])
mat2 = tf.constant([[12,4,1],[6,11,6]])

mat1 @ mat2

# Won't work because of the matrix shape mat1 => (2,3) and mat2 => (2,3)
# shape should be mat1 => (2,3) and mat2 => (3,2)

InvalidArgumentError: ignored

In [18]:
# It works
mat1 = tf.constant([[2,3,5],[6,1,3]])
mat2 = tf.constant([[12,4],[1,6],[11,6]])

mat1 @ mat2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 82,  56],
       [106,  48]], dtype=int32)>

In [21]:
Y = tf.constant([[1,2],[3,4],[5,6]])
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [3]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [4]:
# Transpose of a matrix

tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [5]:
# Dot Product

tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [6]:
Y.shape

TensorShape([3, 2])

In [7]:
# Reshape the matrix 

tf.reshape(Y, (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [8]:
print("Normal Y:")
print(Y, "\n") 

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


### Changing Dtype of Tensor

In [9]:
X = tf.constant([10,2])
X

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  2], dtype=int32)>

In [10]:
S = tf.cast(X, dtype=tf.float32)
S

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  2.], dtype=float32)>

In [11]:
# Absolute Values using 

neg_tensor = tf.constant([-9,-2])
tf.abs(neg_tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 2], dtype=int32)>

### Find Max, Min, Sum and Mean on Tensor

In [16]:
np_arr = np.random.randint(low=30,high=2000,size=100)

In [18]:
tensor = tf.constant(np_arr)

In [19]:
# Min

tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=36>

In [20]:
# Max

tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=1998>

In [21]:
# Sum

tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=96827>

In [22]:
# Mean

tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=968>

### Find Index of min and max values

In [23]:
# Min value index

tf.argmin(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [24]:
tensor[47]

<tf.Tensor: shape=(), dtype=int64, numpy=36>

In [25]:
# Max value index
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=37>

In [26]:
tensor[37]

<tf.Tensor: shape=(), dtype=int64, numpy=1998>

### Squeeze the tensor

In [27]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim


(TensorShape([1, 1, 1, 1, 50]), 5)

In [28]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
array([[[[[96, 79, 80, 65, 25, 39, 30, 25, 68, 76, 44, 26, 83, 60, 84,
           60, 42, 61, 76, 72, 55, 46, 85, 89, 47, 96, 60, 29, 27,  2,
           10, 21, 25, 24, 21, 48, 30, 21, 66, 46, 21, 31, 48, 25, 83,
           83, 90, 93, 11,  8]]]]])>

In [31]:
squeezed_G = tf.squeeze(G)
squeezed_G

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([96, 79, 80, 65, 25, 39, 30, 25, 68, 76, 44, 26, 83, 60, 84, 60, 42,
       61, 76, 72, 55, 46, 85, 89, 47, 96, 60, 29, 27,  2, 10, 21, 25, 24,
       21, 48, 30, 21, 66, 46, 21, 31, 48, 25, 83, 83, 90, 93, 11,  8])>

In [32]:
squeezed_G.shape

TensorShape([50])

### One hot Encoding

In [35]:
num = [1,2,3,4]

tf.one_hot(num, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

### Square, Log and Square Root

In [36]:
tensor = tf.constant(np.random.randint(low=10,high=100, size=30))
tensor

<tf.Tensor: shape=(30,), dtype=int64, numpy=
array([78, 25, 90, 36, 22, 93, 52, 18, 83, 52, 82, 94, 35, 74, 96, 26, 34,
       85, 64, 10, 19, 37, 28, 80, 24, 10, 10, 38, 31, 34])>

In [37]:
tf.square(tensor)

<tf.Tensor: shape=(30,), dtype=int64, numpy=
array([6084,  625, 8100, 1296,  484, 8649, 2704,  324, 6889, 2704, 6724,
       8836, 1225, 5476, 9216,  676, 1156, 7225, 4096,  100,  361, 1369,
        784, 6400,  576,  100,  100, 1444,  961, 1156])>

In [38]:
# Sqrt but first we have to cast tensor to float32

tensor_2 = tf.cast(tensor,dtype=tf.float32)
tf.sqrt(tensor_2)

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([8.83176  , 5.       , 9.486833 , 6.       , 4.6904154, 9.64365  ,
       7.2111025, 4.2426405, 9.110434 , 7.2111025, 9.055385 , 9.695359 ,
       5.9160795, 8.6023245, 9.797958 , 5.0990195, 5.8309517, 9.219544 ,
       8.       , 3.1622777, 4.3588986, 6.0827622, 5.2915025, 8.944271 ,
       4.898979 , 3.1622777, 3.1622777, 6.164414 , 5.5677643, 5.8309517],
      dtype=float32)>

In [40]:
# Log

tf.math.log(tensor_2)

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([4.356709 , 3.218876 , 4.4998097, 3.583519 , 3.0910425, 4.5325994,
       3.9512436, 2.8903718, 4.4188404, 3.9512436, 4.406719 , 4.543295 ,
       3.5553482, 4.304065 , 4.564348 , 3.2580965, 3.5263605, 4.4426513,
       4.158883 , 2.3025851, 2.944439 , 3.610918 , 3.3322046, 4.3820267,
       3.1780539, 2.3025851, 2.3025851, 3.637586 , 3.4339871, 3.5263605],
      dtype=float32)>

In [45]:
# Create (224,224,3) tensor

arr = np.random.rand(224,224,3)
tensor_arr = tf.constant(arr)

tensor_arr.shape

TensorShape([224, 224, 3])